### ISSUE TITLE
Wheel installation in container does not use proxy for git dependencies.

### ISSUE THREAD

**Issue by rpbritton** [canonical/temporal-worker-k8s-operator#20]
### Bug Description

Pip's `--proxy` argument does not pass the proxy to Git ([functionality described here](https://github.com/pypa/pip/issues/227)), so the wheel installation will fail to clone a Git dependency even if `http-proxy` is set.

### To Reproduce

1. Define python sub dependency specified with Git (e.g. `django-rest-generator = { git = "https://github.com/canonical/django-rest-generator.git" }` in `pyproject.toml`)
2. Set `http-proxy`, `https-proxy`, `no-proxy`  in configuration file as needed.
3. Pip installation of wheel dependencies fails.

### Environment

`latest/stable` on a machine that requires an HTTP proxy.

### Relevant log output

```shell
unit-temporal-worker-k8s-0: 19:25:32 ERROR unit.temporal-worker-k8s/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 516, in <module>
    main.main(TemporalWorkerK8SOperatorCharm)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/main.py", line 456, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/framework.py", line 943, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/src/log.py", line 41, in decorated
    return method(self, event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 98, in _on_config_changed
    self._update(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 297, in _update
    self._validate(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 269, in _validate
    self._process_wheel_file(event)
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 223, in _process_wheel_file
    _install_wheel_file(
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/./src/charm.py", line 448, in _install_wheel_file
    _, error = container.exec(command).wait_output()
  File "/var/lib/juju/agents/unit-temporal-worker-k8s-0/charm/venv/ops/pebble.py", line 1540, in wait_output
    raise ExecError[AnyStr](self._command, exit_code, out_value, err_value)
ops.pebble.ExecError: non-zero exit code 1 executing ['pip', 'install', '--proxy=http://XXXXXXX:3128', '/user_provided/sqa_artifact_scheduler-1.0.0-py3-none-any.whl'], stdout="Processing /user_provided/sqa_artifact_scheduler-1.0.0-py3-none-any.whl\nCollecting django-rest-generator@ git+https://github.com/canonical/django-rest-generator.git\n  Cloning https://github.com/canonical/django-rest-generator.git to /tmp/pip-install-vkedz15c/django-rest-generator_3409f8a2bac24923889287b415afcc27\n  Resolved https://github.com/canonical/django-rest-generator.git to commit cda0d661f9a473625fc39556f34ee317c6af7650\n  Installing build dependencies: started\n  Installing build dependencies: still running...\n  Installing build dependencies: still running...\n  Installing build dependencies: still running...\n  Installing build dependencies: still running...\n  Installing build dependencies: still running...\n  Installing build dependencies: still running...\n  Installing build dependencies: finished with status 'error'\n", stderr="  Running command git clone --filter=blob:none --quiet https://github.com/canonical/django-rest-generator.git /tmp/pip-install-vkedz15c/django-rest-generator_3409f8a2bac24923889287b415afcc27\n  error: subprocess-exited-with-error\n  \n  × pip subprocess to install build dependencies did not run successfully.\n  │ exit code: 1\n  ╰─> [7 lines of output]\n      WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffbcdab1340>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/setuptools/\n      WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffbcdab16d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/setuptools/\n      WARNING: Retrying (Retry(total=2, connec" [truncated]
unit-temporal-worker-k8s-0: 19:25:33 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

Setting `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` in the environment for the install in `_install_wheel_file` should resolve this.

**Comment by gtato** [comment]
@rpbritton This [PR](https://github.com/canonical/temporal-worker-k8s-operator/pull/19) is supposed to make the worker charm accept rocks instead of wheels, and the proxy won't be an issue, since the rock can be built locally.

**Comment by rpbritton** [comment]
Sounds good, I will mark this closed
